
services:
  portfolio:
    build: 
      context: ../portfolio-ps
      dockerfile: Dockerfile
    container_name: portfolio-app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`popa-stefan.be`) && PathPrefix(`/portfolio`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio.service=portfolio"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.routers.portfolio.priority=10"
      - "traefik.http.routers.portfolio.middlewares=portfolio-strip@docker"
      - "traefik.http.middlewares.portfolio-strip.stripprefix.prefixes=/portfolio"
    networks:
      - starcozka-app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  starcozka-app-network:
       external: true